# dev_dependencies:
#   flutter_test:
#     sdk: flutter
#   flutter_lints: ^3.0.0
# name: road
# description: Road Distress Detection App
# version: 1.0.0

# environment:
#   sdk: '^3.9.0'

# dependencies:
#   share_plus: ^11.1.0
#   ffmpeg_kit_flutter_new_video: ^1.1.0
#   flutter:
#     sdk: flutter
#   camera: ^0.10.6
#   video_player: ^2.9.1
#   image_picker: ^1.1.2
#   tflite_flutter: ^0.11.0
#   geolocator: ^13.0.1
#   geocoding: ^3.0.0
#   path_provider: ^2.1.4
#   permission_handler: ^11.3.1
#   pdf: ^3.11.1
#   printing: ^5.13.4
#   intl: ^0.19.0
#   pdfx: ^2.6.0
#   video_thumbnail: ^0.5.0
#   open_filex: ^4.3.2
#   image: ^4.0.15
#   flutter_image_compress: ^1.1.0
#   collection: ^1.17.0
#   logger: ^1.1.0
#   async: ^2.11.0
#   http: ^1.1.0

# flutter:
#   uses-material-design: true

#   assets:
#     - assets/road_distress_model.tflite
#     - assets/labels.txt
#     - assets/guide.pdf
#     - assets/documentation.pdf
name: road
description: Road Distress Detection App
version: 1.0.0

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  share_plus: ^11.1.0
  ffmpeg_kit_flutter_new_video: ^1.1.0
  camera: ^0.10.6
  video_player: ^2.9.1
  image_picker: ^0.8.7+6
  tflite_flutter: ^0.11.0
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  pdf: ^3.11.1
  printing: ^5.13.4
  intl: ^0.19.0
  pdfx: ^2.6.0
  video_thumbnail: ^0.5.0
  open_filex: ^4.3.2
  image: ^4.5.4
  flutter_image_compress: ^2.2.0
  collection: ^1.17.0
  logger: ^1.1.0
  async: ^2.11.0
  http: ^1.1.0
  video_frame_extractor: ^0.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/road_distress_float.tflite
    - assets/labels.txt
    - assets/guide.pdf
    - assets/documentation.pdf

